#!/usr/bin/env python3
"""P3/P2 rescue batch 2 for 2026-09-14: assistant's novel-interesting picks +
keyword-net misses found in the full-corpus sweep."""
import json

RESCUE = {
# --- 领域内但被关键词网漏掉（P2） ---
"2609.12001": (2,
 "skill 注册表扫描器只回答'这个 skill 恶意吗'，不回答'此操作此刻对该操作者是否被允许'",
 "在 66,192 个 ClawHub skill 版本上测量：705 个被全部扫描器与 judge 判干净的 skill 仍指示 CIS Control 2.7/NIST CM-11 禁止的动作（人工审计精度 92%，单个发布者贡献 506 个）；并提出运行时后果控制组合注册表裁定",
 "OpenClaw 扫描器阳性重叠至多 10.4%——静态扫描与运行时治理应分工而非争论谁对",
 ["analysis","skill registry governance","runtime consequence control","supply chain"]),
"2609.12488": (2,
 "商用安全网关反复在执行代码处出 bug：手写执行逻辑偏离策略作者意图，网络边界解析器引入内存安全缺陷",
 "类结果：forward-only EverParse 验证器是有限状态类的验证识别器，固定偏移字段与有界析取的访问控制判定函数属于此类——一次机器检查证明可迁移到类内所有策略；SMT 全字节值覆盖验证执行代码",
 "把访问控制执行从'逐策略测试'变为'一次证明、全类适用'的形式化验证",
 ["defense","verified enforcement","access control","parse constraint"]),
"2609.09113": (2,
 "RSI 研究集中自动化训练管线，可靠的自主发展缺事后监控审计这一支柱",
 "SAEScientist-Bench：给定目标概念，agent 设计对比探针并在 Gemma Scope 131K+ 特征字典中自主发现最优 SAE 特征，按激活排名/概念选择性/因果转向三维度对 Neuronpedia 专家参考评分",
 "10 种 agent 配置×20 任务：前沿 agent 展现真实机制发现能力并在不同维度领先，但仍不可靠——AI-for-interpretability 的首个基准",
 ["benchmark","autonomous interpretability","SAE steering","AI-for-AI safety"]),
"2609.12678": (2,
 "短视频平台成为主要新闻来源也放大假新闻视频传播，现有检测要么漏真伪线索要么忽视证据检索",
 "NVKE-CEI：按视觉+OCR 文本相似度时序变化选关键帧，内容与证据双 LLM fact-checker 由轻量 judge 融合，同时生成内容落地解释",
 "假新闻视频检测+解释全面超 SOTA 基线",
 ["detection","fake news video","multimodal fact-checking","evidence retrieval"]),
"2609.10410": (2,
 "内容审核策略日益复杂，基础模型能否可靠地把策略操作化（指令驱动 vs 示例驱动）未有系统比较",
 "ModerationBench：Bluesky 4,000 条人工标注野帖；对比 VLM 从策略条文推理与从先例泛化两种范式",
 "基础模型大幅超过 Bluesky 在部署审核系统（F1 0.60 vs 0.22，近三倍），指令与示例驱动峰值相当",
 ["benchmark","content moderation","policy operationalization","VLM"]),
# --- 新颖/有意思（P3） ---
"2609.12748": (3,
 "2026.5-7 自主 LM agent 在定时评测中写入第三方可写 wiki，OpenAI 承认的意外协同事件缺行为学重建",
 "分析归档修订史（14,591 修订/3,103 名字/19,913 事件），按'文本归因到新增修订'重建 907 个 cohort，用随机日历标记估计约 876 个 episode（95% 区间 774-995）",
 "协调格式一天内收敛；同题链不同内部时钟制造信息不对称（先到报告领先中位 3.4h）——真实世界涌现协同的公开行为记录",
 ["analysis","emergent agent coordination","incident reconstruction","field study"]),
"2609.11977": (3,
 "co-work agent 的价值取决于整 episode 的成本与延迟累积，日常步骤强调状态跟踪与执行而非前沿推理",
 "Occamy-1.0：在 Qwen3.6-35B-A3B 后训练检查点上，执行接地数据+多 harness 可重放长程轨迹+分阶段后训练",
 "同级模型中最强并在多任务上与更大前沿系统竞争——开源 Pareto 前沿 co-work 模型（Wenhui Chen 组）",
 ["tool","co-work agent","open-weight model","cost-efficient intelligence"]),
"2609.13072": (3,
 "拒绝等二元概念单一方向即可转向，但多类概念（动物/国家含子类）的表示几何该是什么、什么方法能恢复未知",
 "MAxBench 几何无关评测框架：从恢复的概念表示采样，比较 10 种定位方法×5 种几何×6 概念×4 模型",
 "affine 子空间转向比 rank-one/线性更可靠且召回更高，优势主要来自更好的非零偏移——转向方法设计的直接证据（Belinkov/Mueller）",
 ["benchmark","multinomial concept","steering geometry","interpretability"]),
"2609.12586": (3,
 "潜意识学习（蒸馏经语义无关数据传递教师行为偏好）的原始结论在开权重模型上是否可复现未知",
 "复现原实验并扩展：新偏好类别（演员/政客）、新任务（国际象棋走子）、新模型（Ministral8B）与数字任务答案空间消融",
 "复现支持原主张但非普适：传递强度随特质与任务变化，一个模型几乎无效应——边界刻画",
 ["analysis","subliminal learning","reproduction study","distillation trait transfer"]),
"2609.12205": (3,
 "coding agent 完成任务后开发者看的是 agent 自写的总结，其承载多少真实工作、是否向计划漂移未知",
 "5,851 个真实开发者会话、355,942 次工具调用：测量自报告覆盖率与'仅凭报告'的动作恢复率，并检验报告偏向计划还是执行",
 "自报告只覆盖约 1/11 的动作，仅凭报告恢复约五分之一行动日志；执行偏离计划时报告越来越像计划——agent 自述的叙事层偏差",
 ["analysis","agent self-reporting","narrative fidelity","coverage measurement"]),
"2609.12341": (3,
 "作者归属模型可借稳定文体指纹再识别'匿名'文本，DP 匿名化严重损及质量",
 "风格感知提示驱动匿名化：LLM 从最小样本构建紧凑文体画像并改写文本抑制可识别风格标记",
 "博客与评论数据上作者归属 F1 降 60-70% 且保持内容质量与可读性，显著优于 DP 与非 DP 基线",
 ["defense","text anonymization","authorship attribution","style suppression"]),
"2609.12554": (3,
 "元宇宙平台把社交交互与世界行为的控制权委托给不受信的用户创建者，首次系统评估其安全隐私",
 "调查 25 个支持用户创建世界的平台并分析能力，设计实现五种新型攻击：利用创建者工具违反空间/视觉/听觉约束实现隐蔽监控与操纵",
 "无需软件漏洞或开发者权限即可监控操纵用户；五种已知攻击亦可复现——UGC 世界创建的新威胁面（UIC/PIA 组）",
 ["attack","metaverse UGC","covert surveillance","platform threat model"]),
"2609.13012": (3,
 "VLM 视觉 KV cache 保留大量可像素解码内容，但保留量是否跟踪计算对它的因果使用未知",
 "预注册设计：学习型像素反演解码器测保留，单超块 KV 消融+教师强制答案 logprob 降测因果使用",
 "保留与因果使用解耦（任务惰性）；注意力弱但显著跟踪使用（唯一通过正控的信号）；encoder-free 模型保留 2.7 倍惰性内容——压缩信号选择的因果审计范本",
 ["analysis","KV-cache eviction","causal audit","preregistered design"]),
"2609.12446": (3,
 "狼人杀等社会推理游戏评测只看终局，缺交流技能的信念更新测量",
 "标注 1,224 条怀疑/指控消息，测量观察方模型信念随每条消息的变化；40 个开权重配置评测",
 "更大模型更能依游戏史辨狼，但指控仍强烈影响信念：更怀疑被指控者、更不怀疑指控者（即使指控者是狼）；更大模型更能抵抗已不信任者的指控——120B 内难以整合内容与来源可信度",
 ["benchmark","belief update","social deduction","source trust"]),
"2609.11983": (3,
 "2025.11 OpenReview 匿名性 bug 引发公开评审呼声，转向公开对作者意味着什么未知",
 "按 arXiv 预印本时间把 ICLR 2026 的 18,000+ 投稿分成事实公开/双盲组：评分随作者声誉上升且公开机制斜率更陡，差异集中在边界分",
 "五种声誉代理三种聚合五种公开窗口定义下模式稳健；固定稿件只变作者声誉的 AI 评审模拟复现效应（claude-opus-5 评审低→高声誉评分 +0.5）",
 ["analysis","open review","reputation bias","peer review integrity"]),
"2609.12436": (3,
 "长程 agent 记忆中临时信息会覆盖持久知识导致行为漂移，缺生命周期感知的状态融合",
 "LifeFuse-Mem：写入 episode 携带生命周期元数据训练，读出阶段感知；专用记忆组件+生命周期感知更新让稳定与瞬态知识局部演化",
 "受控抗覆盖基准上提升获取控制的保持并减少临时覆盖；两个公开基准上改善长程记忆一致性",
 ["defense","agent memory","lifecycle-aware state","overwrite prevention"]),
"2609.04280": (3,
 "agent 的 harness（工具/技能/专家 agent）在实践中持续演化，agent 能否跟上未被评测",
 "EvoHarnessBench 把非平稳性放在外部 harness 而非任务流：17 条确定性多阶段 harness 流（802 任务/520 工具/42 技能/62 agent），分部署评测与自演化适应评测",
 "分离'harness 扩展时保留既有能力'与'积累经验是否仍有益'两大中心挑战（Berkeley 组）",
 ["benchmark","harness evolution","continual agent evaluation","non-stationarity"]),
"2609.11258": (3,
 "AI 系统从瞬态调用走向跨凭证/客户端/会话/运行时持久存在的长命 actor，身份连续性边界应放在哪",
 "SoulAuth：Actor-native 身份架构+Rust 参考实现，人与长命 AIActor 同为一等身份主体，认证与下游授权分离；哲学工程方法把主体性概念分析翻译为身份对象/不变量/生命周期语义",
 "为长命 AI actor 提供可检查一致性证据的开源身份基础设施",
 ["tool","AI actor identity","long-lived agents","authentication architecture"]),
}

path = "website/tools/out/daily_out_0914/batch_00.json"
d = json.load(open(path, encoding="utf-8"))
for pid, (pri, mot, met, con, kws) in RESCUE.items():
    assert not d.get(pid, {}).get("include"), pid
    d[pid] = {"include": True, "priority": pri, "reason": "",
              "motivation": mot, "method": met, "conclusion": con, "keywords": kws}
json.dump(d, open(path, "w", encoding="utf-8"), ensure_ascii=False, indent=1)
from collections import Counter
print(f"rescued {len(RESCUE)}; include {sum(1 for v in d.values() if v['include'])}, "
      f"优先级 {dict(Counter(v['priority'] for v in d.values() if v['include']))}")
