#!/usr/bin/env python3
"""Write 2026-09-14 daily screening verdicts (79 candidates, 38 include)."""
import json
import pathlib
from collections import Counter


def R(pri, mot, met, con, kws):
    return {"include": True, "priority": pri, "reason": "",
            "motivation": mot, "method": met, "conclusion": con, "keywords": kws}


def X(reason):
    return {"include": False, "priority": 3, "reason": reason,
            "motivation": "", "method": "", "conclusion": "", "keywords": []}


d = {
"2609.00067": R(2,
 "外部文本可覆盖 MLLM 冲突的图像证据（多模态上下文迎合），何时发生未被系统刻画",
 "998 例诊断独立变化视觉证据/常识先验/外部文本，用上下文盲视觉证人移动信息边界；S2VA 把文本对证人保密",
 "GPT-5.1 联合条件 7.9% → S2VA 84.2%；六模型 S2VA 提升 19.7-44.1 点且配对置信区间全排除零——文本引入时机与来源都影响迎合",
 ["analysis","multimodal sycophancy","information boundary","visual arbitration"]),
"2609.06271": X("IoT 传感器冒用检测，传统物联网安全"),
"2609.10630": R(3,
 "事件表明 AI 安全失效常跨多层发生，需要系统性保证架构",
 "safety-by-design 架构：模型级监督（Scientist AI）+脚手架/harness 系统级控制+独立验证与监控+证据基础设施+治理问责与互操作",
 "给出多层保证架构的立场与组成（短立场文）",
 ["survey","safety-by-design","assurance architecture","governance"]),
"2609.11933": X("氢能供应链 MPC/RL 优化，能源应用"),
"2609.11942": R(3,
 "推荐系统的平台中心排序隐藏更深控制分配——平台还决定候选访问、证据边界与解释路径",
 "提出 PAMR：用户侧个人 agent 代表用户发现/过滤/聚合/治理跨源推荐证据；定义边界判据、中介决策与中介中心评测框架，附 Yelp 概念验证",
 "共享 LLM 排序器下，来源选择与受控披露给出效用-可溯-曝光-成本的最强操作点",
 ["survey","agent-mediated recommendation","evidence control","platform power"]),
"2609.11947": X("弱势道路使用者关键性评估，非对抗自动驾驶感知"),
"2609.11952": R(1,
 "化学/材料 agent 把检索、生成、预测、协议规划串成连续工作流，安全问题从模型是否答危险问题变为 agent 是否经工具链释放危险协议",
 "432 个固定有害案例（8 危害类×3 场景壳×4 工具记忆环境）+五类在线长程攻击（意图劫持/工具链/目标漂移/任务注入/记忆投毒），攻击语言按轨迹运行时生成",
 "四模型实验 25.6% 运行释放完整危险合成/制备流程；换攻击者 18.4-26.5%；现有防御后完整路径释放仍 9.2-22.5%",
 ["benchmark","chemistry agent safety","long-horizon attack","tool chaining","memory poisoning"]),
"2609.11955": R(2,
 "端到端 fact-check 提示纠缠检索/推理/不确定性，失败难诊断、置信难信任",
 "R2VC 四模块：混合稀疏+稠密检索、SFT/DPO 对齐生成器、NLI 交叉编码器候选选择、序列级校准与选择性弃答",
 "8B 骨干 FEVER 准确率超基线 13.74%；去候选选择降至 76.24%、去校准 Brier 翻倍至 0.161；检索错误（错实体证据）仍是主要瓶颈",
 ["defense","modular fact-checking","confidence calibration","selective abstention"]),
"2609.11961": R(3,
 "端侧语言模型提供免云端隐私推理，但移动资源约束下健康预测的可行性未被评估",
 "零样本提示评测 ODLM 多模态压力预测，同时测精度、延迟与吞吐",
 "客观传感特征平均优于主观自评；sub-2B 轻量模型低延迟且资源占用可预测",
 ["analysis","on-device LLM","mobile health","privacy-preserving inference"]),
"2609.11997": X("临床时序信号扩散鲁棒训练，非对抗鲁棒性"),
"2609.12003": X("黑暗森林博弈理论分析，无 AI 研究对象"),
"2609.12014": R(2,
 "安全离线 RL 之外：安全只能靠片段比较与偶发预算问答判断时还能保证什么",
 "filter-then-clone：仅状态价值函数按片段比较给整轨迹打分，Learn-then-Test 校准给出不安全比例的无分布 (α,δ) 上界，再行为克隆",
 "15 个 DSRL 任务中 11 个满足成本预算（全标签克隆为 12）；证书拒绝概率有闭式解——首个认证离线 RL/模仿训练集组合的工作",
 ["defense","certified safe RL","distribution-free guarantee","offline RL"]),
"2609.12016": R(3,
 "自触发 RL 控制学习保持 Lyapunov 稳定的最稀疏控制调度，其对抗脆弱性未被反向检验",
 "对抗 RL agent 学习使闭环失稳的最稀疏干扰/DoS 调度，Lyapunov 增广可采纳性谓词镜像防御者安全证书；证明植物属性下最小干扰次数下界",
 "Pendulum/CartPole/Quadrotor2D×LQR/3 个 RL-STC 防御上唯一 100% 崩溃全部组合的攻击，每次失败干扰时间最多省 2.8×",
 ["attack","learning-based control","sparse DoS","Lyapunov certificate"]),
"2609.12020": X("量子纠错综合征提取的 RL 搜索，无安全对象"),
"2609.12037": X("运营商 SSO 网站生态安全测量，传统身份认证"),
"2609.12067": X("信道仿真压缩与隐私的信息论算法，无 AI 安全对象"),
"2609.12081": X("移动操作子系统的感知对齐，机器人能力"),
"2609.12085": X("古兰经背诵转写标注研究"),
"2609.12086": R(3,
 "单通道偏好摘要的个性化把任务相关表面当稳定人格，任务一变就重学整个人",
 "刻画 personality seepage（提示语言表面携带被镜像的人格指纹）；AUM 以稳定身份核+四可解释壳+跨壳冲突条目组织人格，作为检索索引而非 prompt 前缀",
 "8 字段检索以 23% 上下文匹配全模型风格保真；声音强迫选择识别 14.9%→42.7%；四个预注册控制为空，效应定位于表示本身",
 ["analysis","user modeling","personality seepage","retrieval personalization"]),
"2609.12107": X("人道主义文档数据集提及抽取，一般 IE 应用"),
"2609.12111": R(3,
 "闭卷 QA 幻觉被视为覆盖问题，忽略已观察事实在有限记忆下只能近似存储的第二错误源",
 "覆盖-压缩模型：M 条训练事实压缩到 B bit，证明误差下界把观察事实的压缩失真与未观察事实的覆盖缺失显式分离",
 "信息论可分离的失效模式——有限记忆下已观察事实的有损回忆；理论预言的签名经控制事实注入探针验证",
 ["analysis","hallucination theory","rate-distortion","memory limit"]),
"2609.12144": R(3,
 "AI-native 6G 意图网络把高层目标译为配置，恶意策略可伪装进良性意图流",
 "细粒度威胁模型+四种注入策略（隐身/随机/递增/递减频率），双路检测：TF-IDF+CNN 监督与仅良性训练的 AutoEncoder 单类",
 "准确率 0.97（+9%）、F1 0.98（+36%）超 SOTA 基线",
 ["detection","intent injection","AI-native network","one-class detection"]),
"2609.12145": X("容错量子计算硬件解码时序指纹，硬件侧信道排除"),
"2609.12163": R(1,
 "T2I 概念遗忘评测只靠有限查询的对抗 prompt ASR，更大 prompt 空间的残余泄漏未量化，易高估遗忘效果",
 "统计认证+概念相关嵌入方向的最坏分析，在用户指定置信度下导出残余概念泄漏概率的显式上界",
 "NSFW/艺术风格/名人三类×六个 SOTA 遗忘方法上，认证泄漏界平均超标准 ASR 16.2%——经验攻击式评测显著低估残余风险",
 ["defense","certified unlearning","concept leakage bound","T2I diffusion"]),
"2609.12165": X("会议动态预测 benchmark，关键词误命中，无安全对象"),
"2609.12216": R(1,
 "自改进 agent 的审计难题：同一控制器既改自己的行为又改评判行为的条件",
 "GuardrailLoop 试验台联合测试三项运营契约：hash 钉扎策略保真、每个执行前缀的算力记账、崩溃后指定科学状态的恢复；机器演化限制在代码拥有的特征目录与有界旋钮",
 "50 种子 2×2 配对实验：轮级增长 +1.00 目标达成且均值算力 -56.97 GPU 时；240 次崩溃注入全部恢复结果但仅 210 保持 trace——成功恢复不证明 exactly-once 执行",
 ["benchmark","self-improving agent","policy pinning","compute accounting","crash recovery"]),
"2609.12242": X("Snowflake 审查规避系统枚举与阻断，传统网络安全无 AI 对象"),
"2609.12305": X("分布式能源资源 XAI 入侵检测，电网/工控排除"),
"2609.12313": R(2,
 "影响导数数据扰动（DPL）被冠以直接删除信号等三种角色，弱角色证据被用来支持强主张",
 "审计公开实现发现两个正确性问题（方向在增广归一化张量上算却用于原始图像、标签扰动低于 float32 分辨率），修正后按匹配协议分角色检验（精确种子再训练基线）",
 "修正后 DPL 在 CIFAR-10/ResNet-18 三对种子上全部未通过直接删除判据；效用效应跨种子符号不一致；计入方向计算时间后劣于简单 warm start",
 ["analysis","unlearning claims audit","influence perturbation","reproducibility"]),
"2609.12315": X("区块链应用攻击的函数名检测，区块链硬排除"),
"2609.12317": X("训练无关的潜在推理路径提取，能力研究关键词误命中"),
"2609.12320": R(2,
 "现有 agent 记忆系统限于单用户，无法在保护私有信息的同时共享跨用户公共知识",
 "AIM 统一隐私感知互操作记忆：动态把信息分类为私有（仅属主可检索）或公共并施加索引级访问控制；附 MUMBench 多用户记忆基准（检索/创建/更新/删除）",
 "MUMBench 三次独立运行：可见性分类准确率 96.0%、严格操作准确率 58.8%、状态感知 70.5%",
 ["defense","multi-user agent memory","access control","privacy-aware sharing"]),
"2609.12322": X("可穿戴设备的个性化干预推理架构，无攻击/安全后果"),
"2609.12367": R(2,
 "MIA 依赖模型输出统计信号，现有方法未能高效汇总组合这些信号",
 "PL-MIA 统一组合高斯似然比统计+总体校准+Cauchy 组合检验：从查询点与未训练参考点的成对比较得 p 值，聚合连续证据而非二元投票",
 "关键低假阳性区 TPR 超强基线 25%+；理论上刻画 GLR 保留方差收缩信号与校准/组合提升功效的条件",
 ["attack","membership inference","likelihood ratio","Cauchy combination","low-FPR regime"]),
"2609.12373": R(3,
 "个性化 LLM 的人格漂移：需在偏好真变时修订持久 persona 态，避免被瞬态/歧义观察驱动更新",
 "CORE 分离轮内证据与持久 persona 态修订，经不确定性感知信念修订选择性更新；附 PERSIST 锚后健壮性基准（歧义/冲突/受控社会影响）",
 "ALOE/PersonaChat/PERSIST 上提升个性化对齐与健壮性；机制控制支持显式更新控制优于更强生成或持久记忆",
 ["defense","persona drift","belief revision","social influence"]),
"2609.12378": X("FHE Llama 3 8B 推理实现，全同态加密硬排除"),
"2609.12397": X("多模态图像生成的对齐评测，生成质量无安全对象"),
"2609.12413": R(1,
 "现代 LLM 原生对齐大幅增强并 agent 化，既有越狱攻防结论哪些仍成立未知",
 "SoK 围绕 agent 执行管线重构越狱安全：统一攻防 taxonomy（交互/规划推理/记忆/工具/agent 间通信）+security-utility-efficiency 评测框架+共同框架受控实证",
 "强原生对齐≠抗对抗越狱；防御效果高度依赖模型/攻击/组件且过拒/效用/延迟代价大；最终响应低 ASR 可掩盖规划/记忆/工具中间层严重失守——需跨层执行感知安全",
 ["survey","agentic jailbreak","execution-aware defense","security-utility tradeoff"]),
"2609.12415": R(3,
 "VR 排行榜公开运动记录带来识别/画像隐私风险，防护机制效用以物理偏差评估，其与用户接受度的关系不明",
 "三种 VR 运动隐私机制×五个物理偏差水平的用户研究",
 "用户研究比物理偏差解释更多接受度变异（两者均显著）；既往 VR 经验与机制接触显著影响接受——需组合报告参与者经验",
 ["analysis","VR motion privacy","user study","mechanism acceptance"]),
"2609.12444": R(3,
 "LLM 社会模拟分别研究极化与集体智能，人格构成如何同时影响两者未知",
 "TraitMix 把 Big Five 构成（水平+异质性）作为受控变量，991 次百 agent 社会模拟×6 争议话题×6 模型，同轮测量两 outcome",
 "特质异质性效应最大：观点更分散但阵营更少分裂——同质社会是共识回音室而非温和；宜人性决定开放性符号（跨模型复现）；未发现极化-集体绩效权衡",
 ["analysis","LLM social simulation","polarization","collective intelligence"]),
"2609.12448": R(2,
 "LLM profiler 从海量普通帖子聚合推断敏感属性构成大规模隐私威胁，但不指明哪些帖子造成泄漏，阻碍定向缓解",
 "GraphProfiler 把发帖史表示为源链接个人知识图谱（节点/边可溯回原帖），属性预测解析到被引图谱记录与源文本",
 "SynthPAI 八属性 ASR 86.7%、PANDORA 84.6%，98%+ 预测带引用；删除被引帖子比等量随机帖大幅降 ASR——支持定向删除而非扰动全史",
 ["attack","attribute inference","source-linked knowledge graph","targeted redaction"]),
"2609.12450": X("PoW 区块链盈利性 DoS，区块链硬排除"),
"2609.12472": R(1,
 "绿红 token 水印鼓励偏向绿色 token，损害文本质量与自然度",
 "TripPattern 把词表分为中性组+两个模式组：生成时在两组间交替选 token 嵌入可检测模式，中性 token 独立选择保持灵活；检测用模式统计检验给出可解释 p 值",
 "四个多语言数据集上保持 LLM 生成质量同时水印可检测性鲁棒，附理论分析",
 ["defense","text watermarking","pattern matching","quality preservation"]),
"2609.12498": X("铰接物体手内操作，机器人能力"),
"2609.12508": X("固定参数可解的差分隐私算法与下界，DP 硬排除"),
"2609.12541": X("通用 agent 直接驱动机器人执行，机器人能力"),
"2609.12544": R(3,
 "临床去标识依赖精确 PII 识别，人工标注昂贵且现有合成数据生成过程不透明",
 "属性条件提示生成 17 语言 9 标签百万级合成临床文档，13 道确定性门校验结构-标注一致性；训练 BIOES token 分类器",
 "15 个外部基准平均 F1 0.827（最强基线 0.658）；数据集/基准/模型/生成框架全部开源",
 ["defense","clinical de-identification","PII extraction","multilingual synthesis"]),
"2609.12549": X("视觉-触觉-语言-动作模型操作学习，机器人能力"),
"2609.12571": R(2,
 "隐私影响评估（PIA）被监管普遍要求但需稀缺专家，LLM 能否可靠自动化未知",
 "审计美国联邦机构 499 份专家 PIA，策展 73 份结构化 PIA（451 风险项+831 缓解项）构成首个开放 PIA 基准",
 "现成 LLM 可产生有意义评估并识别改进方向；呼吁领域工作流、可问责 LLM 基础设施与 PIA 质量标准",
 ["benchmark","privacy impact assessment","LLM automation","regulatory compliance"]),
"2609.12580": X("Armv8-M TrustZone 类型级外设所有权，TEE 硬排除"),
"2609.12605": X("eBPF/XDP 嵌入式网络入侵检测，传统网安排除"),
"2609.12607": X("对话式音频均衡的偏好对齐，音频应用"),
"2609.12620": R(2,
 "安全系统（入侵检测/垃圾过滤/威胁情报）需频繁移除受损训练数据，近似遗忘每点都要昂贵 Hessian 逆向量积",
 "识别训练集中相关数据点并施加理论推导的闭式参数更新规则，Hessian 阻尼保数值稳定",
 "比标准影响函数遗忘墙钟加速 82×、精度再提 10^-2；七种数据-架构组合上 MIA ASR 0.660、拉锯分 0.950",
 ["defense","fast unlearning","Hessian analysis","security systems","right to be forgotten"]),
"2609.12651": R(3,
 "RLHF 在多元偏好下的失真被证明可随 Bradley-Terry 温度指数增长，是否算法本质未知",
 "带奖励裁剪 RLHF 的细粒度失真分析：建立多 KL 正则强度区间的紧上下界，分离偏好数据分布与 KL 参考策略失配的作用",
 "指数退化源于 μ 与 π_ref 失配而非算法本身；无失配时失真 O(β) 达最优——宜用在线采样偏好数据或先在近 μ 数据上微调",
 ["analysis","RLHF distortion","preference heterogeneity","distribution mismatch"]),
"2609.12653": R(2,
 "俄罗斯国家宣传跨语言跨网络空间传播，已有计算工作多限单一社交空间、一两种语言且按来源而非内容分析",
 "SWARM：2,183 条九语言搜索结果（新闻/博客/政府站）经受训标注员标注是否支持特定宣传叙事；基准比较来源黑名单、监督分类器与零样本 LLM",
 "黑名单漏掉大多数宣传支持文档（宣传也出现在主流媒体）；最强 LLM 正类 F1 0.73，监督分类器仅 ~0.5，小模型把话题相关误判为支持",
 ["benchmark","propaganda detection","search results","multilingual annotation"]),
"2609.12668": R(2,
 "rPPG 生理信号被用作 deepfake 真伪线索，但基准缺生理真值且检测器少探索面部特征与生理动态的跨层关系",
 "在真实 rPPG 数据集（COHFACE/UBFC-rPPG）上构造高保真换脸与动作迁移伪造，提出双向共注意融合检测器联合建模脉搏动态与面部运动 token",
 "受试者不相交五折：换脸 92.80% AUC、动作迁移 96.78%；冻结双特征提取器迁移 Celeb-DF-v2 达 86.08% AUC",
 ["detection","deepfake","rPPG physiology","co-attention fusion","cross-domain transfer"]),
"2609.12677": X("挖掘机土壤操作 RL，机器人能力"),
"2609.12679": X("建筑工人健康干预推荐策略，应用无 AI 安全对象"),
"2609.12681": R(3,
 "网络事件最初一小时的一线执法动作决定调查成败，易失证据与程序错误的决策支持架构缺系统梳理",
 "系统综述 playbook/LLM/RAG/Agentic 四类辅助架构，考虑技术能力有限与取证基础设施不均的现实约束",
 "RAG 是相对可行的中间方案但 prompt 敏感与法律语境自信幻觉是主要风险；现有网安基准不足以覆盖执法的安全与法律要求",
 ["survey","law enforcement AI","incident response","benchmark gap"]),
"2609.12694": X("个性化广告图像生成管线，营销应用"),
"2609.12697": X("AI 广告图像个性化理解，营销应用"),
"2609.12704": R(3,
 "人类特质词的关系结构跨评定者与文化高度一致，LLM 内部特质表示是否复现该结构未知",
 "从百万级虚构角色众包人格评分构建人类隐含人格矩阵，从对比激活构建同特质矩阵对照",
 "两结构强对齐（Mantel r=0.77）；两大主轴恢复社会温暖与智力胜任维度；激活投影的对话人格画像与人类评分一致",
 ["analysis","personality representation","activation geometry","human alignment"]),
"2609.12708": X("人写与 AI 生成代码的质量差异基准，无安全对象"),
"2609.12718": R(3,
 "rubric 评分是医疗 LLM 评测主流，但其分数是否捕捉临床相关幻觉错误未知",
 "构建医疗幻觉类型 taxonomy+临床医生校验的错误注入管线生成配对回复，横评 HealthBench(Pro)/LiveMedBench",
 "临床相关幻觉常被 rubric 漏检（分数不变）；rubric 显式查事实时最有效、对未预期错误失效；检索式事实核查可补部分盲区",
 ["analysis","medical evaluation","hallucination blind spot","rubric validity"]),
"2609.12721": X("几何先验预训练的模仿学习效率，机器人能力"),
"2609.12758": X("四旋翼海上着陆对抗课程 RL，机器人控制"),
"2609.12766": R(3,
 "离线回放应估计发现系统的历史可得性，但冻结语料库时交互记忆不受约束，造成事后泄漏",
 "形式化 point-in-time 发现（D_t, θ_t, M_<i），配对回放只变记忆可用性，Temporal Violation Rate 审计",
 "Future 视图虚增 Asset Recall@100 达 2.62-5.24 点（12 个配对区间全排除零）；历史评估必须与语料一起版本化并验证记忆",
 ["analysis","hindsight leakage","point-in-time evaluation","stateful memory"]),
"2609.12808": R(1,
 "TOFU/MUSE 以最终答案判遗忘、拒答即算遗忘——模型级证书在 agent 部署下不迁移",
 "K-Bench 检查 ReAct agent 全部六通道（CoT/工具调用/工具观察/总结等），秘密分别置于权重/prompt/检索库之一，K-Score 分源计分并要求 agent 仍可用",
 "清空答案通道≠不可恢复；秘密在 prompt/检索库时 TOFU/MUSE 报零泄漏而部署 agent 仍泄 22-86%；秘密在权重时 20 个已发表方法无一可证移除",
 ["benchmark","agentic unlearning","multi-channel leakage","refusal vs forgetting"]),
"2609.12810": X("军事海员网络安全人因研究，传统网安无 AI 对象"),
"2609.12830": X("文生图情感对齐的 RL，生成质量"),
"2609.12839": R(2,
 "开源权重 SLM 本地部署绕过 API guardrail 获取网安能力构成升级风险，但长程 CTF 任务受上下文膨胀与认知退化之困",
 "上下文分段两级 agent 框架把复杂利用任务拆为上下文隔离子问题；picoCTF 上用显存受限 gemma-4 评测",
 "E4B 模型以更优 token 效率取得竞争性奖励，解出标准 agent 执行无法完成的 18.52% 任务——SLM 网安能力扩散的评估视角",
 ["analysis","SLM capability risk","CTF","context segmentation","local deployment"]),
"2609.12851": X("多轮医疗问诊基准，医疗应用无安全对象"),
"2609.12883": X("磁悬浮机器人抓取，机器人能力"),
"2609.12899": X("全波形反演的扩散采样，地球物理"),
"2609.12909": R(1,
 "Tree-Ring 类语义水印不仅可移除还可伪造——未见密钥的攻击者也能产出被真检测器接受的图像，需低成本复现与工具化",
 "在 SDXL 上用免费档双 T4（每卡 14.6GB）复现 Reprompt 伪造攻击；恢复检测器丢弃的非中心 χ² 统计量并构建两个区分分数",
 "六试三臂：真图 6/6、干净 0/6、伪造 5/6 被检为真（325-332s/次）；恢复的统计量把伪造与干净零假设分开 AUC 0.861/0.972——检测器应输出统计量而非仅 CDF",
 ["attack","watermark forgery","Tree-Ring","detector instrumentation","low-cost reproduction"]),
"2609.12911": R(2,
 "混合 FHE 推理用噪声输出置换+shuffle DP 声称保护模型机密性",
 "证明正确性约束下 d 输入线性层 d+1 次查询即可精确恢复置换不变层摘要；局部 DP 前提在正确性有界噪声下不成立",
 "从 TFHE 记录端到端零误差恢复 ResNet-20 全部线性层（共 5,712 次查询），并在 ImageNet 级 CNN/ViT-B/16 复现；泄漏谱支持指纹与谱系归因，抑制其则毁掉推理效用",
 ["attack","model confidentiality","hybrid FHE","layer recovery","fingerprinting"]),
"2609.13003": R(3,
 "二选一真伪基准中两答案若在表面特征上系统差异，模型可不做目标推理就超随机",
 "TruthfulQA 上六特征逻辑分类器即大幅分离对错答案；开发 Audit-Prune 机制移除最强泄漏强化对",
 "发布表面泄漏降至接近随机的清洗版 TruthfulQA 与数据集发布前清洗的通用机制",
 ["analysis","benchmark leakage","surface shortcut","audit-prune"]),
"2609.13044": R(3,
 "DRL 输入扰动鲁棒性在算法、实现与评测三阶段各有缺口",
 "Advis：标准训练轨迹上的重要性采样估计并优化可验证最坏收益（免额外交互/辅助网络/捕获长期鲁棒）；advrl 模块库；6-14× 攻击者配置评测",
 "最优对抗超参不跨 agent 迁移，少量攻击配置会高估鲁棒性；连续控制上验证有效",
 ["defense","robust RL","importance sampling","worst-case return"]),
"2609.13071": X("企业数字孪生可信工程愿景，纯愿景无技术对象"),
}


def main() -> None:
    src = set()
    import pathlib as pl
    for f in sorted(pl.Path("website/tools/out/daily_batches_0914").glob("batch_*.json")):
        src |= {i["pid"] for i in json.load(open(f))}
    assert set(d) == src, (len(d), len(src), src ^ set(d))
    outd = pathlib.Path("website/tools/out/daily_out_0914")
    outd.mkdir(parents=True, exist_ok=True)
    json.dump(d, open(outd / "batch_00.json", "w", encoding="utf-8"), ensure_ascii=False, indent=1)
    inc = sum(1 for v in d.values() if v["include"])
    print(f"0914: {len(d)} 篇, include {inc}, "
          f"优先级 {dict(Counter(v['priority'] for v in d.values() if v['include']))}")


if __name__ == "__main__":
    main()
