#!/usr/bin/env python3
"""Validate, search, and generate views for the paper knowledge base."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
import unicodedata
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import urlparse


ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
PAPERS_PATH = DATA_DIR / "papers.jsonl"
TAXONOMY_PATH = DATA_DIR / "taxonomy.json"
COLLECTIONS_DIR = DATA_DIR / "collections"
GENERATED_MARKER = "<!-- Generated by scripts/library.py. Do not edit manually. -->"
PAPER_ID_RE = re.compile(r"^\d{4}-[a-z0-9]+(?:-[a-z0-9]+)*$")
SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
ARXIV_RE = re.compile(
    r"^(?:\d{4}\.\d{4,5}|[a-z][a-z0-9.-]*/\d{7})$",
    re.IGNORECASE,
)


class RepositoryError(Exception):
    """Raised when source data cannot be loaded."""


@dataclass
class Repository:
    taxonomy: dict[str, Any]
    papers: list[dict[str, Any]]
    collections: list[dict[str, Any]]

    @property
    def paper_by_id(self) -> dict[str, dict[str, Any]]:
        return {paper["id"]: paper for paper in self.papers if isinstance(paper.get("id"), str)}

    @property
    def domain_by_id(self) -> dict[str, dict[str, Any]]:
        return {domain["id"]: domain for domain in self.taxonomy.get("domains", [])}

    @property
    def topic_to_domain(self) -> dict[str, str]:
        result: dict[str, str] = {}
        for domain in self.taxonomy.get("domains", []):
            for topic in domain.get("topics", []):
                result[topic["id"]] = domain["id"]
        return result


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise RepositoryError(f"Missing required file: {path.relative_to(ROOT)}") from exc
    except json.JSONDecodeError as exc:
        raise RepositoryError(f"Invalid JSON in {path.relative_to(ROOT)}:{exc.lineno}: {exc.msg}") from exc
    if not isinstance(value, dict):
        raise RepositoryError(f"Expected an object in {path.relative_to(ROOT)}")
    return value


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError as exc:
        raise RepositoryError(f"Missing required file: {path.relative_to(ROOT)}") from exc

    rows: list[dict[str, Any]] = []
    for line_number, line in enumerate(lines, 1):
        if not line.strip():
            continue
        try:
            row = json.loads(line)
        except json.JSONDecodeError as exc:
            raise RepositoryError(
                f"Invalid JSON in {path.relative_to(ROOT)}:{line_number}: {exc.msg}"
            ) from exc
        if not isinstance(row, dict):
            raise RepositoryError(f"Expected an object in {path.relative_to(ROOT)}:{line_number}")
        row["_line"] = line_number
        rows.append(row)
    return rows


def load_collections() -> list[dict[str, Any]]:
    if not COLLECTIONS_DIR.exists():
        return []
    collections: list[dict[str, Any]] = []
    for path in sorted(COLLECTIONS_DIR.rglob("*.json")):
        collection = load_json(path)
        collection["_path"] = path.relative_to(ROOT).as_posix()
        collections.append(collection)
    return collections


def load_repository() -> Repository:
    return Repository(load_json(TAXONOMY_PATH), load_jsonl(PAPERS_PATH), load_collections())


def normalize_title(title: str) -> str:
    normalized = unicodedata.normalize("NFKD", title).casefold()
    return "".join(character for character in normalized if character.isalnum())


def normalize_doi(doi: str) -> str:
    value = doi.strip().casefold()
    for prefix in ("https://doi.org/", "http://doi.org/", "doi:"):
        if value.startswith(prefix):
            value = value[len(prefix) :]
    return value


def normalize_arxiv(arxiv_id: str) -> str:
    value = arxiv_id.strip()
    value = re.sub(r"^arxiv:", "", value, flags=re.IGNORECASE)
    value = re.sub(r"v\d+$", "", value, flags=re.IGNORECASE)
    return value


def valid_url(value: str) -> bool:
    parsed = urlparse(value)
    return parsed.scheme in {"http", "https"} and bool(parsed.netloc)


def valid_iso_date(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    try:
        return dt.date.fromisoformat(value).isoformat() == value
    except ValueError:
        return False


def _require_fields(item: dict[str, Any], fields: Iterable[str], label: str, errors: list[str]) -> None:
    for field in fields:
        if field not in item:
            errors.append(f"{label}: missing field '{field}'")


def validate_taxonomy(repo: Repository) -> list[str]:
    errors: list[str] = []
    taxonomy = repo.taxonomy
    if taxonomy.get("schema_version") != 1:
        errors.append("data/taxonomy.json: schema_version must be 1")

    for enum_name in ("levels", "resource_types", "importance", "review_statuses"):
        values = taxonomy.get(enum_name)
        if not isinstance(values, list) or not values or not all(isinstance(value, str) for value in values):
            errors.append(f"data/taxonomy.json: '{enum_name}' must be a non-empty string list")

    domains = taxonomy.get("domains")
    if not isinstance(domains, list) or not domains:
        return errors + ["data/taxonomy.json: 'domains' must be a non-empty list"]

    seen_domains: set[str] = set()
    seen_topics: set[str] = set()
    for index, domain in enumerate(domains):
        label = f"data/taxonomy.json domain[{index}]"
        if not isinstance(domain, dict):
            errors.append(f"{label}: expected an object")
            continue
        _require_fields(domain, ("id", "name", "name_zh", "description_zh", "keywords", "topics"), label, errors)
        domain_id = domain.get("id")
        if not isinstance(domain_id, str) or not SLUG_RE.fullmatch(domain_id):
            errors.append(f"{label}: invalid id '{domain_id}'")
        elif domain_id in seen_domains:
            errors.append(f"{label}: duplicate domain id '{domain_id}'")
        else:
            seen_domains.add(domain_id)
        for field in ("name", "name_zh", "description_zh"):
            if not isinstance(domain.get(field), str) or not domain.get(field, "").strip():
                errors.append(f"{label}: {field} must be a non-empty string")
        if (
            not isinstance(domain.get("keywords"), list)
            or not domain.get("keywords")
            or not all(isinstance(keyword, str) and keyword.strip() for keyword in domain["keywords"])
        ):
            errors.append(f"{label}: keywords must be a non-empty list")
        topics = domain.get("topics")
        if not isinstance(topics, list) or not topics:
            errors.append(f"{label}: topics must be a non-empty list")
            continue
        for topic_index, topic in enumerate(topics):
            topic_label = f"{label} topic[{topic_index}]"
            if not isinstance(topic, dict):
                errors.append(f"{topic_label}: expected an object")
                continue
            _require_fields(topic, ("id", "name_zh"), topic_label, errors)
            topic_id = topic.get("id")
            if not isinstance(topic_id, str) or not SLUG_RE.fullmatch(topic_id):
                errors.append(f"{topic_label}: invalid id '{topic_id}'")
            elif topic_id in seen_topics:
                errors.append(f"{topic_label}: duplicate topic id '{topic_id}'")
            else:
                seen_topics.add(topic_id)
            if not isinstance(topic.get("name_zh"), str) or not topic.get("name_zh", "").strip():
                errors.append(f"{topic_label}: name_zh must be a non-empty string")
    return errors


def validate_papers(repo: Repository) -> list[str]:
    errors: list[str] = []
    taxonomy = repo.taxonomy
    valid_domains = set(repo.domain_by_id)
    topic_to_domain = repo.topic_to_domain
    valid_levels = set(taxonomy.get("levels", []))
    valid_types = set(taxonomy.get("resource_types", []))
    valid_importance = set(taxonomy.get("importance", []))
    valid_statuses = set(taxonomy.get("review_statuses", []))
    seen_ids: dict[str, str] = {}
    seen_dois: dict[str, str] = {}
    seen_arxiv: dict[str, str] = {}
    seen_titles: dict[str, str] = {}
    required = (
        "id", "title", "authors", "year", "venue", "resource_type", "identifiers", "urls",
        "domains", "topics", "level", "importance", "review_status", "summary_zh", "note_path",
        "added", "updated",
    )

    for index, paper in enumerate(repo.papers):
        paper_id = paper.get("id", f"line-{paper.get('_line', index + 1)}")
        label = f"paper '{paper_id}'"
        _require_fields(paper, required, label, errors)
        if not isinstance(paper_id, str) or not PAPER_ID_RE.fullmatch(paper_id):
            errors.append(f"{label}: invalid id")
        elif paper_id in seen_ids:
            errors.append(f"{label}: duplicate id also used by {seen_ids[paper_id]}")
        else:
            seen_ids[paper_id] = label

        title = paper.get("title")
        if not isinstance(title, str) or not title.strip():
            errors.append(f"{label}: title must be a non-empty string")
        else:
            normalized_title = normalize_title(title)
            if normalized_title in seen_titles:
                errors.append(f"{label}: duplicate normalized title also used by {seen_titles[normalized_title]}")
            else:
                seen_titles[normalized_title] = paper_id

        authors = paper.get("authors")
        if not isinstance(authors, list) or not authors or not all(isinstance(author, str) and author for author in authors):
            errors.append(f"{label}: authors must be a non-empty string list")

        year = paper.get("year")
        if type(year) is not int or not 1940 <= year <= dt.date.today().year + 1:
            errors.append(f"{label}: invalid year '{year}'")

        venue = paper.get("venue")
        if not isinstance(venue, str) or not venue.strip():
            errors.append(f"{label}: venue must be a non-empty string")

        if paper.get("resource_type") not in valid_types:
            errors.append(f"{label}: unknown resource_type '{paper.get('resource_type')}'")
        if paper.get("level") not in valid_levels:
            errors.append(f"{label}: unknown level '{paper.get('level')}'")
        if paper.get("importance") not in valid_importance:
            errors.append(f"{label}: unknown importance '{paper.get('importance')}'")
        if paper.get("review_status") not in valid_statuses:
            errors.append(f"{label}: unknown review_status '{paper.get('review_status')}'")

        domains = paper.get("domains")
        if not isinstance(domains, list) or not domains:
            errors.append(f"{label}: domains must be a non-empty list")
            domains = []
        elif not all(isinstance(domain_id, str) for domain_id in domains):
            errors.append(f"{label}: domains must contain only string IDs")
            domains = [domain_id for domain_id in domains if isinstance(domain_id, str)]
        elif len(domains) != len(set(domains)):
            errors.append(f"{label}: domains contains duplicates")
        for domain_id in domains:
            if domain_id not in valid_domains:
                errors.append(f"{label}: unknown domain '{domain_id}'")

        topics = paper.get("topics")
        if not isinstance(topics, list) or not topics:
            errors.append(f"{label}: topics must be a non-empty list")
            topics = []
        elif not all(isinstance(topic_id, str) for topic_id in topics):
            errors.append(f"{label}: topics must contain only string IDs")
            topics = [topic_id for topic_id in topics if isinstance(topic_id, str)]
        elif len(topics) != len(set(topics)):
            errors.append(f"{label}: topics contains duplicates")
        for topic_id in topics:
            parent_domain = topic_to_domain.get(topic_id)
            if parent_domain is None:
                errors.append(f"{label}: unknown topic '{topic_id}'")
            elif parent_domain not in domains:
                errors.append(f"{label}: topic '{topic_id}' requires domain '{parent_domain}'")

        identifiers = paper.get("identifiers")
        if not isinstance(identifiers, dict):
            errors.append(f"{label}: identifiers must be an object")
        else:
            doi = identifiers.get("doi")
            if doi is not None:
                if not isinstance(doi, str) or not normalize_doi(doi).startswith("10."):
                    errors.append(f"{label}: invalid DOI '{doi}'")
                else:
                    normalized_doi = normalize_doi(doi)
                    if normalized_doi in seen_dois:
                        errors.append(f"{label}: duplicate DOI also used by {seen_dois[normalized_doi]}")
                    else:
                        seen_dois[normalized_doi] = paper_id
            arxiv_id = identifiers.get("arxiv")
            if arxiv_id is not None:
                if not isinstance(arxiv_id, str):
                    errors.append(f"{label}: invalid arXiv ID '{arxiv_id}'")
                    normalized_arxiv = ""
                else:
                    normalized_arxiv = normalize_arxiv(arxiv_id)
                if normalized_arxiv and not ARXIV_RE.fullmatch(normalized_arxiv):
                    errors.append(f"{label}: invalid arXiv ID '{arxiv_id}'")
                elif normalized_arxiv and normalized_arxiv.casefold() in seen_arxiv:
                    errors.append(
                        f"{label}: duplicate arXiv ID also used by {seen_arxiv[normalized_arxiv.casefold()]}"
                    )
                elif normalized_arxiv:
                    seen_arxiv[normalized_arxiv.casefold()] = paper_id

        urls = paper.get("urls")
        if not isinstance(urls, dict) or not isinstance(urls.get("paper"), str):
            errors.append(f"{label}: urls.paper is required")
        elif any(not isinstance(url, str) or not valid_url(url) for url in urls.values()):
            errors.append(f"{label}: every URL must be an absolute http(s) URL")

        summary = paper.get("summary_zh")
        if not isinstance(summary, str) or len(summary.strip()) < 10:
            errors.append(f"{label}: summary_zh is too short")
        for date_field in ("added", "updated"):
            if not valid_iso_date(paper.get(date_field)):
                errors.append(f"{label}: {date_field} must be an ISO date")
        if valid_iso_date(paper.get("added")) and valid_iso_date(paper.get("updated")):
            if paper["updated"] < paper["added"]:
                errors.append(f"{label}: updated cannot be earlier than added")

        note_path = paper.get("note_path")
        if note_path is not None:
            if not isinstance(note_path, str) or not note_path.startswith("papers/") or ".." in Path(note_path).parts:
                errors.append(f"{label}: invalid note_path '{note_path}'")
            elif not (ROOT / note_path).is_file():
                errors.append(f"{label}: note_path does not exist: {note_path}")
    return errors


def expected_collection_path(collection: dict[str, Any]) -> str | None:
    kind = collection.get("kind")
    if kind == "daily" and valid_iso_date(collection.get("date")):
        date = dt.date.fromisoformat(collection["date"])
        return f"data/collections/daily/{date:%Y/%m/%Y-%m-%d}.json"
    if (
        kind == "conference"
        and isinstance(collection.get("venue_id"), str)
        and type(collection.get("conference_year")) is int
    ):
        return f"data/collections/conferences/{collection['venue_id']}/{collection['conference_year']}.json"
    return None


def validate_collections(repo: Repository) -> list[str]:
    errors: list[str] = []
    paper_ids = set(repo.paper_by_id)
    seen_collection_ids: set[str] = set()
    seen_collection_paths: dict[str, str] = {}
    required = (
        "schema_version", "id", "kind", "date", "title", "source_urls", "query_notes",
        "selection_stats", "summary_zh", "items",
    )

    for index, collection in enumerate(repo.collections):
        collection_id = collection.get("id", f"collection-{index + 1}")
        label = f"collection '{collection_id}'"
        _require_fields(collection, required, label, errors)
        if collection.get("schema_version") != 1:
            errors.append(f"{label}: schema_version must be 1")
        if not isinstance(collection_id, str) or not SLUG_RE.fullmatch(collection_id):
            errors.append(f"{label}: invalid id")
        elif collection_id in seen_collection_ids:
            errors.append(f"{label}: duplicate collection id")
        else:
            seen_collection_ids.add(collection_id)
        if not isinstance(collection.get("kind"), str) or collection.get("kind") not in {"daily", "conference"}:
            errors.append(f"{label}: kind must be 'daily' or 'conference'")
        if not valid_iso_date(collection.get("date")):
            errors.append(f"{label}: date must be an ISO date")

        if not isinstance(collection.get("title"), str) or not collection.get("title", "").strip():
            errors.append(f"{label}: title must be a non-empty string")
        for field in ("query_notes", "summary_zh"):
            value = collection.get(field)
            if not isinstance(value, str) or len(value.strip()) < 10:
                errors.append(f"{label}: {field} must contain at least 10 characters")

        expected_path = expected_collection_path(collection)
        actual_path = collection.get("_path")
        if expected_path is not None and actual_path != expected_path:
            errors.append(f"{label}: expected path {expected_path}, found {actual_path}")
        if expected_path is not None:
            previous_id = seen_collection_paths.get(expected_path)
            if previous_id is not None:
                errors.append(f"{label}: output path is already used by collection '{previous_id}'")
            else:
                seen_collection_paths[expected_path] = str(collection_id)

        kind = collection.get("kind")
        if kind == "daily" and valid_iso_date(collection.get("date")):
            expected_id = f"daily-{collection['date']}"
            if collection_id != expected_id:
                errors.append(f"{label}: daily id must be '{expected_id}'")

        source_urls = collection.get("source_urls")
        if not isinstance(source_urls, list) or not source_urls:
            errors.append(f"{label}: source_urls must be a non-empty list")
        elif any(not isinstance(url, str) or not valid_url(url) for url in source_urls):
            errors.append(f"{label}: source_urls contains an invalid URL")

        if kind == "conference":
            venue_id = collection.get("venue_id")
            if not isinstance(venue_id, str) or not SLUG_RE.fullmatch(venue_id):
                errors.append(f"{label}: invalid venue_id")
            conference_year = collection.get("conference_year")
            if type(conference_year) is not int or not 1940 <= conference_year <= dt.date.today().year + 1:
                errors.append(f"{label}: conference_year must be a plausible integer year")
            if isinstance(venue_id, str) and SLUG_RE.fullmatch(venue_id) and type(conference_year) is int:
                expected_id = f"conference-{venue_id}-{conference_year}"
                if collection_id != expected_id:
                    errors.append(f"{label}: conference id must be '{expected_id}'")

        stats = collection.get("selection_stats")
        stat_fields = (
            ("candidates", "new_records", "existing_records", "included")
            if kind == "daily"
            else ("official_total", "candidates", "merged_records", "included")
        )
        if not isinstance(stats, dict):
            errors.append(f"{label}: selection_stats must be an object")
        else:
            for field in stat_fields:
                value = stats.get(field)
                if type(value) is not int or value < 0:
                    errors.append(f"{label}: selection_stats.{field} must be a non-negative integer")
            if all(type(stats.get(field)) is int for field in stat_fields):
                if stats["candidates"] < stats["included"]:
                    errors.append(f"{label}: candidates cannot be lower than included")
                if kind == "daily" and stats["new_records"] + stats["existing_records"] != stats["included"]:
                    errors.append(f"{label}: new_records plus existing_records must equal included")
                if kind == "conference":
                    if stats["official_total"] < stats["candidates"]:
                        errors.append(f"{label}: official_total cannot be lower than candidates")
                    if stats["merged_records"] > stats["included"]:
                        errors.append(f"{label}: merged_records cannot exceed included")

        items = collection.get("items")
        if not isinstance(items, list):
            errors.append(f"{label}: items must be a list")
            continue
        if isinstance(stats, dict) and stats.get("included") != len(items):
            errors.append(f"{label}: selection_stats.included must equal the number of items")
        seen_items: set[str] = set()
        for item_index, item in enumerate(items):
            item_label = f"{label} item[{item_index}]"
            if not isinstance(item, dict):
                errors.append(f"{item_label}: expected an object")
                continue
            _require_fields(item, ("paper_id", "reason_zh"), item_label, errors)
            paper_id = item.get("paper_id")
            if not isinstance(paper_id, str):
                errors.append(f"{item_label}: paper_id must be a string")
            elif paper_id not in paper_ids:
                errors.append(f"{item_label}: unknown paper_id '{paper_id}'")
            if isinstance(paper_id, str) and paper_id in seen_items:
                errors.append(f"{item_label}: duplicate paper_id '{paper_id}'")
            elif isinstance(paper_id, str):
                seen_items.add(paper_id)
            reason = item.get("reason_zh")
            if not isinstance(reason, str) or len(reason.strip()) < 5:
                errors.append(f"{item_label}: reason_zh is too short")
    return errors


def validate_repository(repo: Repository) -> list[str]:
    taxonomy_errors = validate_taxonomy(repo)
    if taxonomy_errors:
        return taxonomy_errors
    return validate_papers(repo) + validate_collections(repo)


def markdown_escape(value: Any) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def authors_display(paper: dict[str, Any]) -> str:
    authors = paper["authors"]
    if len(authors) <= 3:
        return ", ".join(authors)
    return f"{', '.join(authors[:3])}, et al."


def note_link(paper: dict[str, Any], prefix: str) -> str:
    note_path = paper.get("note_path")
    return f"[笔记]({prefix}{note_path})" if note_path else "—"


def domain_links(paper: dict[str, Any], repo: Repository, prefix: str) -> str:
    links = []
    for domain_id in paper["domains"]:
        domain = repo.domain_by_id[domain_id]
        links.append(f"[{domain['name_zh']}]({prefix}{domain_id}.md)")
    return "、".join(links)


def paper_table(papers: list[dict[str, Any]], repo: Repository, domain_prefix: str, note_prefix: str) -> str:
    if not papers:
        return "暂无收录。\n"
    lines = [
        "| 论文 | 年份 | 作者 | venue | 领域 | 级别 | 资源 | 笔记 |",
        "| --- | ---: | --- | --- | --- | --- | --- | --- |",
    ]
    for paper in sorted(papers, key=lambda item: (-item["year"], item["title"].casefold())):
        title = f"<a id=\"{paper['id']}\"></a>[{markdown_escape(paper['title'])}]({paper['urls']['paper']})"
        lines.append(
            "| "
            + " | ".join(
                (
                    title,
                    str(paper["year"]),
                    markdown_escape(authors_display(paper)),
                    markdown_escape(paper["venue"]),
                    domain_links(paper, repo, domain_prefix),
                    paper["level"],
                    paper["resource_type"],
                    note_link(paper, note_prefix),
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def render_library(repo: Repository) -> str:
    note_count = sum(bool(paper.get("note_path")) for paper in repo.papers)
    content = [
        "# 全部论文目录",
        "",
        GENERATED_MARKER,
        "",
        f"当前收录 **{len(repo.papers)}** 条资源，其中 **{note_count}** 条已有详细笔记。",
        "",
        "可使用 `python3 scripts/library.py search --help` 进行组合筛选。",
        "",
        paper_table(repo.papers, repo, "../domains/", "../"),
    ]
    return "\n".join(content).rstrip() + "\n"


def render_domain_index(repo: Repository) -> str:
    counts = Counter(domain_id for paper in repo.papers for domain_id in paper["domains"])
    lines = [
        "# 领域地图",
        "",
        GENERATED_MARKER,
        "",
        "一篇论文可以属于多个领域。数量代表当前覆盖，不代表领域重要性。",
        "",
        "| 领域 | 范围 | 论文数 |",
        "| --- | --- | ---: |",
    ]
    for domain in repo.taxonomy["domains"]:
        lines.append(
            f"| [{domain['name_zh']} / {domain['name']}]({domain['id']}.md) | "
            f"{markdown_escape(domain['description_zh'])} | {counts[domain['id']]} |"
        )
    return "\n".join(lines) + "\n"


def render_domain_page(domain: dict[str, Any], repo: Repository) -> str:
    papers = [paper for paper in repo.papers if domain["id"] in paper["domains"]]
    topic_counts = Counter(topic_id for paper in papers for topic_id in paper["topics"])
    lines = [
        f"# {domain['name_zh']} / {domain['name']}",
        "",
        GENERATED_MARKER,
        "",
        domain["description_zh"],
        "",
        "## 子主题",
        "",
        "| 子主题 | 当前收录 |",
        "| --- | ---: |",
    ]
    for topic in domain["topics"]:
        lines.append(f"| <a id=\"{topic['id']}\"></a>`{topic['id']}` {topic['name_zh']} | {topic_counts[topic['id']]} |")
    lines.extend(
        (
            "",
            "## 日常检索词",
            "",
            "、".join(f"`{keyword}`" for keyword in domain["keywords"]),
            "",
            "## 收录资源",
            "",
            paper_table(papers, repo, "", "../"),
        )
    )
    return "\n".join(lines).rstrip() + "\n"


def collection_memberships(repo: Repository) -> dict[str, set[str]]:
    memberships: dict[str, set[str]] = defaultdict(set)
    for collection in repo.collections:
        for item in collection.get("items", []):
            paper_id = item.get("paper_id")
            if isinstance(paper_id, str):
                memberships[paper_id].add(collection["kind"])
    return memberships


def render_collection_index(kind: str, repo: Repository) -> str:
    is_daily = kind == "daily"
    title = "每日 arXiv 汇总" if is_daily else "会议论文汇总"
    collections = [collection for collection in repo.collections if collection["kind"] == kind]
    collections.sort(key=lambda item: (item["date"], item["id"]), reverse=True)
    lines = [f"# {title}", "", GENERATED_MARKER, ""]
    if is_daily:
        lines.append("每个页面对应一次按日期冻结的 arXiv 采集批次。")
    else:
        lines.append("每个页面对应一届会议的官方录用列表筛选结果。参见 [会议追踪清单](watchlist.md)。")
    lines.extend(("", "| 批次 | 日期 | 收录数 |", "| --- | --- | ---: |"))
    if not collections:
        lines.append("| 暂无采集批次 | — | 0 |")
    for collection in collections:
        if is_daily:
            date = dt.date.fromisoformat(collection["date"])
            path = f"{date:%Y/%m/%Y-%m-%d}.md"
        else:
            path = f"{collection['venue_id']}/{collection['conference_year']}.md"
        lines.append(f"| [{markdown_escape(collection['title'])}]({path}) | {collection['date']} | {len(collection['items'])} |")
    return "\n".join(lines) + "\n"


def render_collection_page(collection: dict[str, Any], repo: Repository) -> str:
    paper_by_id = repo.paper_by_id
    is_daily = collection["kind"] == "daily"
    root_prefix = "../../../" if is_daily else "../../"
    lines = [
        f"# {collection['title']}",
        "",
        GENERATED_MARKER,
        "",
        f"- 采集日期：`{collection['date']}`",
    ]
    if not is_daily:
        lines.append(f"- 会议：`{collection['venue_id']}` `{collection['conference_year']}`")
    lines.extend(("- 一手来源：" + "、".join(f"[source {index + 1}]({url})" for index, url in enumerate(collection["source_urls"])), ""))
    if collection.get("query_notes"):
        lines.extend(("## 检索说明", "", collection["query_notes"], ""))
    stats = collection["selection_stats"]
    stat_labels = (
        (
            ("candidates", "候选"),
            ("new_records", "新增记录"),
            ("existing_records", "已有记录"),
            ("included", "最终收录"),
        )
        if is_daily
        else (
            ("official_total", "官方列表"),
            ("candidates", "初筛候选"),
            ("merged_records", "合并预印本"),
            ("included", "最终收录"),
        )
    )
    lines.extend(("## 筛选统计", "", "| 阶段 | 数量 |", "| --- | ---: |"))
    for key, display_name in stat_labels:
        lines.append(f"| {display_name} | {stats[key]} |")
    lines.append("")
    if collection.get("summary_zh"):
        lines.extend(("## 批次总结", "", collection["summary_zh"], ""))
    lines.extend(("## 收录论文", ""))
    if not collection["items"]:
        lines.append("本批次没有通过相关性核验的论文。")
    else:
        lines.extend(("| 论文 | 年份 | 领域 | 收录理由 | 笔记 |", "| --- | ---: | --- | --- | --- |"))
        for item in collection["items"]:
            paper = paper_by_id[item["paper_id"]]
            domains = domain_links(paper, repo, f"{root_prefix}domains/")
            lines.append(
                f"| [{markdown_escape(paper['title'])}]({paper['urls']['paper']}) | {paper['year']} | "
                f"{domains} | {markdown_escape(item['reason_zh'])} | {note_link(paper, root_prefix)} |"
            )
    return "\n".join(lines).rstrip() + "\n"


def render_outputs(repo: Repository) -> dict[Path, str]:
    outputs: dict[Path, str] = {
        ROOT / "library" / "README.md": render_library(repo),
        ROOT / "domains" / "README.md": render_domain_index(repo),
        ROOT / "daily" / "README.md": render_collection_index("daily", repo),
        ROOT / "conferences" / "README.md": render_collection_index("conference", repo),
    }
    for domain in repo.taxonomy["domains"]:
        outputs[ROOT / "domains" / f"{domain['id']}.md"] = render_domain_page(domain, repo)
    for collection in repo.collections:
        if collection["kind"] == "daily":
            date = dt.date.fromisoformat(collection["date"])
            output_path = ROOT / "daily" / f"{date:%Y/%m/%Y-%m-%d}.md"
        else:
            output_path = ROOT / "conferences" / collection["venue_id"] / f"{collection['conference_year']}.md"
        outputs[output_path] = render_collection_page(collection, repo)
    return outputs


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def generated_differences(outputs: dict[Path, str]) -> list[str]:
    differences = []
    for path, expected in outputs.items():
        relative = path.relative_to(ROOT).as_posix()
        if not path.exists():
            differences.append(f"missing generated file: {relative}")
        elif path.read_text(encoding="utf-8") != expected:
            differences.append(f"stale generated file: {relative}")
    expected_paths = set(outputs)
    for directory in (ROOT / "library", ROOT / "domains", ROOT / "daily", ROOT / "conferences"):
        if not directory.exists():
            continue
        for path in directory.rglob("*.md"):
            if path in expected_paths:
                continue
            try:
                is_generated = GENERATED_MARKER in path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                is_generated = False
            if is_generated:
                differences.append(f"orphaned generated file: {path.relative_to(ROOT).as_posix()}")
    return differences


def select_papers(
    repo: Repository,
    query: str = "",
    domain: str | None = None,
    topic: str | None = None,
    level: str | None = None,
    year_from: int | None = None,
    year_to: int | None = None,
    collection: str | None = None,
    arxiv: str | None = None,
    doi: str | None = None,
) -> list[dict[str, Any]]:
    memberships = collection_memberships(repo)
    query_terms = [term.casefold() for term in query.split() if term]
    selected = []
    for paper in repo.papers:
        haystack = " ".join(
            [paper["title"], " ".join(paper["authors"]), paper["venue"], paper["summary_zh"], *paper["domains"], *paper["topics"]]
        ).casefold()
        if query_terms and not all(term in haystack for term in query_terms):
            continue
        if domain and domain not in paper["domains"]:
            continue
        if topic and topic not in paper["topics"]:
            continue
        if level and level != paper["level"]:
            continue
        if year_from is not None and paper["year"] < year_from:
            continue
        if year_to is not None and paper["year"] > year_to:
            continue
        if collection and collection not in memberships.get(paper["id"], set()):
            continue
        if arxiv and normalize_arxiv(str(paper["identifiers"].get("arxiv", ""))).casefold() != normalize_arxiv(arxiv).casefold():
            continue
        if doi and normalize_doi(str(paper["identifiers"].get("doi", ""))) != normalize_doi(doi):
            continue
        selected.append(paper)
    return sorted(selected, key=lambda item: (-item["year"], item["title"].casefold()))


def print_errors(errors: list[str]) -> None:
    for error in errors:
        print(f"ERROR: {error}", file=sys.stderr)


def command_check(repo: Repository) -> int:
    errors = validate_repository(repo)
    if errors:
        print_errors(errors)
        return 1
    print(f"OK: {len(repo.papers)} papers, {len(repo.collections)} collections, {len(repo.domain_by_id)} domains")
    return 0


def command_build(repo: Repository) -> int:
    errors = validate_repository(repo)
    if errors:
        print_errors(errors)
        return 1
    outputs = render_outputs(repo)
    write_outputs(outputs)
    print(f"Wrote {len(outputs)} generated files")
    return 0


def command_check_generated(repo: Repository) -> int:
    errors = validate_repository(repo)
    if errors:
        print_errors(errors)
        return 1
    differences = generated_differences(render_outputs(repo))
    if differences:
        print_errors(differences)
        return 1
    print("OK: generated files are current")
    return 0


def command_search(repo: Repository, args: argparse.Namespace) -> int:
    repository_errors = validate_repository(repo)
    if repository_errors:
        print_errors(repository_errors)
        return 1
    filter_errors = []
    if args.domain and args.domain not in repo.domain_by_id:
        filter_errors.append(f"unknown domain '{args.domain}'")
    if args.topic and args.topic not in repo.topic_to_domain:
        filter_errors.append(f"unknown topic '{args.topic}'")
    if args.level and args.level not in repo.taxonomy.get("levels", []):
        filter_errors.append(f"unknown level '{args.level}'")
    if filter_errors:
        print_errors(filter_errors)
        return 2
    papers = select_papers(
        repo,
        query=args.query,
        domain=args.domain,
        topic=args.topic,
        level=args.level,
        year_from=args.year_from,
        year_to=args.year_to,
        collection=args.collection,
        arxiv=args.arxiv,
        doi=args.doi,
    )
    papers = papers[: args.limit]
    print(f"{len(papers)} result(s)")
    for paper in papers:
        print(f"\n{paper['year']}  {paper['title']}")
        print(f"  Authors: {authors_display(paper)}")
        print(f"  Domains: {', '.join(paper['domains'])}")
        print(f"  Level: {paper['level']} | Importance: {paper['importance']}")
        print(f"  URL: {paper['urls']['paper']}")
        print(f"  {paper['summary_zh']}")
    return 0


def command_stats(repo: Repository) -> int:
    errors = validate_repository(repo)
    if errors:
        print_errors(errors)
        return 1
    domain_counts = Counter(domain_id for paper in repo.papers for domain_id in paper["domains"])
    kind_counts = Counter(collection["kind"] for collection in repo.collections)
    print(f"Papers: {len(repo.papers)}")
    print(f"Detailed notes: {sum(bool(paper.get('note_path')) for paper in repo.papers)}")
    print(f"Daily collections: {kind_counts['daily']}")
    print(f"Conference collections: {kind_counts['conference']}")
    print("\nDomain coverage:")
    for domain in repo.taxonomy["domains"]:
        print(f"  {domain['id']:<32} {domain_counts[domain['id']]:>4}")
    return 0


def positive_int(value: str) -> int:
    parsed = int(value)
    if parsed < 1:
        raise argparse.ArgumentTypeError("must be at least 1")
    return parsed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("check", help="validate taxonomy, papers, and collection manifests")
    subparsers.add_parser("build", help="generate library, domain, daily, and conference Markdown views")
    subparsers.add_parser("check-generated", help="fail when generated views are missing or stale")
    subparsers.add_parser("stats", help="show collection and domain coverage")

    search_parser = subparsers.add_parser("search", help="search and filter canonical paper records")
    search_parser.add_argument("query", nargs="?", default="", help="terms matched across title, authors, summary, and tags")
    search_parser.add_argument("--domain", help="exact domain ID from data/taxonomy.json")
    search_parser.add_argument("--topic", help="exact topic ID from data/taxonomy.json")
    search_parser.add_argument("--level", help="exact level from data/taxonomy.json")
    search_parser.add_argument("--year-from", type=int, help="inclusive lower publication year")
    search_parser.add_argument("--year-to", type=int, help="inclusive upper publication year")
    search_parser.add_argument("--collection", choices=("daily", "conference"))
    search_parser.add_argument("--arxiv")
    search_parser.add_argument("--doi")
    search_parser.add_argument("--limit", type=positive_int, default=50)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        repo = load_repository()
    except RepositoryError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    if args.command == "check":
        return command_check(repo)
    if args.command == "build":
        return command_build(repo)
    if args.command == "check-generated":
        return command_check_generated(repo)
    if args.command == "search":
        return command_search(repo, args)
    if args.command == "stats":
        return command_stats(repo)
    parser.error(f"unknown command: {args.command}")
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
